### ISSUE TITLE
`int is not Eventful` crash

### ISSUE THREAD

**Issue by mossberg** [trailofbits/manticore#735]
### OS / Environment
ubuntu 16.04

### Manticore version
5a38737edea4684cf4080c9dda4fe35c7caf43fc

### Python version
2.7

### Summary of the problem

this is some kind of issue related to the event system

```
contract SS {
    address recvr;
    function setme() {
        recvr = msg.sender;
    }
    function sui() {
        suicide(recvr);
    }
}
```

```
[I] mark ubuntu /m/h/c/e/m/play ❯ manticore suic.sol
2018-02-05 15:56:27,640: [72550] m.main:INFO: Beginning analysis
2018-02-05 15:56:27,700: [72550] m.ethereum:INFO: Starting symbolic transaction: 1
2018-02-05 15:56:28,025: [72550] m.ethereum:INFO: Generated testcase No. 0 - REVERT
2018-02-05 15:56:29,756: [72550] m.ethereum:INFO: Generated testcase No. 1 - REVERT
2018-02-05 15:56:31,477: [72550] m.ethereum:INFO: Generated testcase No. 2 - REVERT
2018-02-05 15:56:33,128: [72550] m.ethereum:INFO: Finished symbolic transaction: 1 | Code Coverage: 97% | Terminated States: 4 | Alive States: 2
2018-02-05 15:56:33,139: [72550] m.ethereum:INFO: Starting symbolic transaction: 2
2018-02-05 15:56:33,152: [72550] m.c.executor:ERROR: Exception: int is not Eventful
Traceback (most recent call last):
  File "/mnt/hgfs/code/manticore/manticore/core/executor.py", line 444, in run
    self.forward_events_from(current_state, True)
  File "/mnt/hgfs/code/manticore/manticore/utils/event.py", line 145, in forward_events_from
    raise TypeError('{} is not Eventful'.format(source.__class__.__name__))
TypeError: int is not Eventful

Traceback (most recent call last):
  File "/home/mark/.local/bin/manticore", line 9, in <module>
    load_entry_point('manticore', 'console_scripts', 'manticore')()
  File "/mnt/hgfs/code/manticore/manticore/__main__.py", line 105, in main
    ethereum_cli(args)
  File "/mnt/hgfs/code/manticore/manticore/__main__.py", line 95, in ethereum_cli
    m.multi_tx_analysis(args.argv[0], args.contract, args.txlimit)
  File "/mnt/hgfs/code/manticore/manticore/ethereum.py", line 896, in multi_tx_analysis
    run_symbolic_tx()
  File "/mnt/hgfs/code/manticore/manticore/ethereum.py", line 890, in run_symbolic_tx
    value=symbolic_value )
  File "/mnt/hgfs/code/manticore/manticore/ethereum.py", line 867, in transaction
    status = self.run(procs=self._config_procs)
  File "/mnt/hgfs/code/manticore/manticore/ethereum.py", line 930, in run
    result = super(ManticoreEVM, self).run(**kwargs)
  File "/mnt/hgfs/code/manticore/manticore/manticore.py", line 615, in run
    self._start_workers(procs, profiling=should_profile)
  File "/mnt/hgfs/code/manticore/manticore/manticore.py", line 393, in _start_workers
    target()
  File "/mnt/hgfs/code/manticore/manticore/core/executor.py", line 506, in run
    self._publish('will_terminate_state', current_state, current_state_id, e)
  File "/mnt/hgfs/code/manticore/manticore/utils/event.py", line 117, in _publish
    self._publish_impl(_name, *args, **kwargs)
  File "/mnt/hgfs/code/manticore/manticore/utils/event.py", line 125, in _publish_impl
    callback(robj(), *args, **kwargs)
  File "/mnt/hgfs/code/manticore/manticore/ethereum.py", line 1000, in _terminate_state_callback
    state.context['last_exception'] = e
AttributeError: 'int' object has no attribute 'context'
```

**Comment by mossberg** [comment]
this appears to be a regression introduced by 97307906c5e4d4a89d9631628e6d58f1a19b7e82

**Comment by mossberg** [comment]
looking into this
