### PR TITLE
Typo in ManticoreEVM#last_return

### PR DESCRIPTION
**Pull request by dwhjames**
Encountered the following trace:

```
Traceback (most recent call last):
  …, in <module>
    m.last_return()
  File "…/manticore/ethereum.py", line 906, in last_return
    return state.platform.last_return
AttributeError: 'EVMWorld' object has no attribute 'last_return'
```

It appears this bug was introduced in commit ed29a22f

---
This change is [Reviewable](https://reviewable.io/reviews/trailofbits/manticore/886)

### CODE REVIEW

**Comment by dwhjames** [comment]
`ManticoreEVM#last_return` attempts to call `EVMWorld#last_return`
https://github.com/trailofbits/manticore/blob/9307475af5f52d641e97b8208ac53ea4812e5940/manticore/ethereum.py#L903-L906
but the property is actually
https://github.com/trailofbits/manticore/blob/9307475af5f52d641e97b8208ac53ea4812e5940/manticore/platforms/evm.py#L2049-L2051

**Comment by yan** [comment]
@dwhjames thanks for this pr! It looks like a similar issue exists in [evm.py](https://github.com/trailofbits/manticore/blob/master/manticore/platforms/evm.py#L2243). Update that too and we'll merge?

**Comment by dwhjames** [comment]
So there is, @yan!

I’ve updated that and squashed both changes into a new commit https://github.com/trailofbits/manticore/pull/886/commits/8752b48f4fbf638ce5d9aa235d491c1fe3b03e1a
